### PR TITLE
Added Support in Stories and Achievements Page, of JSON Server along with the Add stories and Achievement Feature | Issue #297

### LINKED ISSUE #297: Create Stories and Achievements Form Implementation to Add more Stories and Achievements| Authenticated for Admin Panels Only
I want to add a form to allow authenticated administrators to add new Stories and Achievements features in the Stories & Achievements Page. The form should be user-friendly and ensure that only users with the proper admin authentication can access and utilize it.

## Requirements:

1. **Authentication**:

- Ensure that only authenticated users with admin privileges can access the form.

2. **Form Fields:**
   - The form should include the following fields:
     - Title (text input)
     - Description (textarea or rich text editor)
     - Date (date picker)
     - Category (dropdown/select, e.g., Story, Achievement)
     - Image Upload (file input for uploading a relevant image)

image

### PR DESCRIPTION
**Pull request by Shariq2003**
fix #297 
I have added the following:-

1. Added JSON Server Support on the Stories and Achievements Page.
2. Implemented Stories and Achievements Addition Page, with a form.

https://github.com/user-attachments/assets/5300c4c8-90e5-4b67-a544-3f92be54682b

### CODE REVIEW

**Comment by rishicds** [comment]
please fix conflicts

**Comment by Shariq2003** [comment]
okay fixing

**Comment by Shariq2003** [comment]
@rishicds please review now.

**Comment by rishicds** [comment]
Merged, good job 🎊

**Pull request merged**
