### PR TITLE
made endpoints

### PR DESCRIPTION
**Pull request by inkerton**
image

#229 
If you feel like removing any info let me know or You have any other field you want to add .

### CODE REVIEW

**Comment by inkerton** [comment]
fetched events
image

fetched Projects
image

I will work on displaying projects now as for events Let me know as I have currently classified them as ongoing, finished, and upcoming. Would that be okay

**Comment by inkerton** [comment]
image

Projects Done PR completed from my side Please just verify the events info and I will make a new page for events according to their status.

**Comment by rishicds** [comment]
please fix the conflicts

**Comment by rishicds** [comment]
hi 240(this) still has conflicts please fix

**Comment by inkerton** [comment]
@rishicds Resolved It was just The id that I added later on

**Comment by inkerton** [comment]
@rishicds Please merge it I have resoved the conflicts already

**Comment by rishicds** [comment]
Merged

**Pull request merged**
