### PR TITLE
Hero Section added:- 4

### PR DESCRIPTION
**Pull request by inkerton**
The hero section I added 
image

This is a simple layout I can change it according to your recommendations later @rishicds

### CODE REVIEW

**Comment by inkerton** [comment]
This is in response to the issue #15

**Comment by inkerton** [comment]
@rishicds Conflict resolved

**Comment by inkerton** [comment]
image
Resolved Commited Please try again First add the footer PR then add hero PR.

@rishicds

**Comment by inkerton** [comment]
resolved

**Comment by Hemu21** [comment]
@MastanSayyad

**Pull request merged**
