### PR TITLE
Created Homepage for mobile and laptop screen

### PR DESCRIPTION
**Pull request by master-ginger**
https://github.com/user-attachments/assets/a09a4c0a-9b9e-4e65-9517-30e154dd5d18

Created the following sections:
1. Catchy/welcome phrase
2. Events
3. Featured projects
4. Google technologies
5. Team members thoughts
6. Footer

### CODE REVIEW

**Comment by rishicds** [comment]
fix merge conflicts @master-ginger

**Comment by master-ginger** [comment]
Done

**Comment by master-ginger** [comment]
Could you please add the hacktoberfest label to the task?

**Comment by master-ginger** [comment]
Hey could you please add the hacktoberfest to the label or else it won't count as a contribution

**Pull request merged**
