### PR TITLE
Designing Error 404 Page

### PR DESCRIPTION
**Pull request by dev129**
### PR Title
**Create Responsive 404 Error Page Using Framer Motion for GDSC RCIIT**

### PR Description
This PR introduces a responsive 404 error page for the GDSC RCIIT project, designed with **Framer Motion** to enhance user experience through smooth animations. The page informs users when a non-existent page is accessed, providing clear messaging and an easy way to return to the homepage. This is for issue #31 .

### Key Features
- **Responsive Design**: The layout adapts to various screen sizes, ensuring accessibility on both desktop and mobile devices.
- **Framer Motion Animations**: Engaging animations for a better user experience.
- **Public Folder for Images**: A **public** folder is included within the **src** directory to store all images used in the project, promoting better organization and future scalability.
- **User Feedback**: Clear messaging indicating that the requested page does not exist, along with a button to return to the homepage.

### Files Modified
- **`src/pages/app/not-found.jsx`**: Implemented a new 404 error page with animations.
- **`src/public/`**: Added a folder for storing images related to the error page.

### Testing Instructions
1. Navigate to any non-existent route within the application to view the 404 error page.
2. Test the page's responsiveness by resizing the browser window or accessing the page on different devices.
3. Click the "Go back to homepage" button to ensure it redirects to the main page.

### Additional Information
- **Dependencies**: Ensure that the `framer-motion` library is installed and mentioned in the project documentation if required.
- **Design Considerations**: If applicable, mention any design guidelines followed in the implementation.

### CODE REVIEW

**Comment by rishicds** [comment]
Please fix the conflicts

**Comment by dev129** [comment]
Fixed It please check

**Comment by rishicds** [comment]
Good job @dev129

**Comment by Shariq2003** [comment]
@rishicds this branch updated the package.json file that contains duplicate keys that cause errors in the main branch

**Comment by rishicds** [comment]
> @rishicds this branch updated the package.json file that contains duplicate keys that cause errors in the main branch

Can you fix it or should I revert

**Comment by Shariq2003** [comment]
image

Look at this, 

image


Contains duplicate dependencies

**Comment by dev129** [comment]
I guess this might be a small.mistake from my side since I am a novice in OSS, but I have removed it fom local machine side

**Comment by Shariq2003** [comment]
> > @rishicds this branch updated the package.json file that contains duplicate keys that cause errors in the main branch
> 
> Can you fix it or should I revert

okay

**Pull request merged**
