### PR TITLE
Projects details Page

### PR DESCRIPTION
**Pull request by inkerton**
https://github.com/user-attachments/assets/8b1f5e68-89e7-4045-a8cb-c3fc749d68bc

@rishicds 
** Please merge after #240  Or conflicts might arise.**

### CODE REVIEW

**Comment by inkerton** [comment]
@rishicds If you want any changes let me know I will do them .

**Comment by rishicds** [comment]
fix conflicts

**Comment by inkerton** [comment]
@rishicds Resolved

**Comment by rishicds** [comment]
Merged

**Pull request merged**
