### PR TITLE
#246 Added  competitive programming track (Roadmap)

### PR DESCRIPTION
**Pull request by pratheekv39**
#### Issue Title
**Please enter the title of the issue related to your pull request.**  
*Enter the issue title here-*
Added  competitive programming track (Roadmap)
- [X] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
*Describe the aim of the project-*
To add the roadmap for competitive programming
- [X] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
*Enter your name here-*
V Pratheek
- [X] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
*Enter your GitHub ID here-*
pratheekv39
- [X] I have provided my GitHub ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hactoberfest).**  
*Enter your participant role here-*
Contributor at GSSOC , Hacktoberfest
- [X] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
*Closes: #issue-number*
#246
- [X] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
*Describe your changes here-*
Added the implementation of Competitive Programming Track
- [X] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
*Describe your testing process here.*

- [X] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.

@rishicds Please see the attached video below for your reference . Thanks :)

https://github.com/user-attachments/assets/6265ea1f-7057-4e51-8ba6-aaf519d0b731

### CODE REVIEW

**Comment by rishicds** [comment]
It does Not follow the Dynamic Routing of Resource Page, as the Resource Page handles the Page Routing by ID, you made the page dependent on the CP content, and breaks other Data support of Resources. Please fix it

**Comment by pratheekv39** [comment]
@rishicds Hi, I have made the following changes:

1) Added a Competitive Programming track following dynamic routing by ID (ID: 6) similar to existing C++ and DSA tracks. I have even corrected the routing of previous roadmaps that I had created . Now , all of the tracks follow dynamic routing.

2)Created separate content files (competitive_programming-content.js and track-contents.js) to maintain proper separation of concerns and consistent structure. track-content.js now also provides segregation to previous tracks as well.

3)Fixed routing dependency by ensuring content is loaded based on resource ID, following the suggested architecture where the Resource Page handles page routing by ID.

Please review the updated commit and if you are satisfied with this change , then please merge the PR . I can then work on my current issue assigned .... Thanks :)

**Comment by rishicds** [comment]
Instead of creating seperate js pages add your content to the resources.js page, take a look at it you'll understand , if it is not possible to shift current page to there let me know.

**Comment by pratheekv39** [comment]
@rishicds I have successfully used  the current  resources.js to add all of my roadmap content . I was able to do it successfully . I have attached the proof of execution below. Kindly , merge the PR ...Thanks :)

https://github.com/user-attachments/assets/14a18fc1-fcbb-4dae-9b25-a9f653a57da1

**Comment by rishicds** [comment]
Done

**Pull request merged**
