### PR TITLE
Routing Implementation | Issue #42

### PR DESCRIPTION
**Pull request by Shariq2003**
I have implemented Routing Successfully, that helps to easily navigate to any pages of the website.

https://github.com/user-attachments/assets/f5ec8b64-203b-4c66-b558-3171b8475db3

@rishicds sir, Upon Successful routing addition I have found that the navigation bar (Header) misfunctioning in many of the cases and also contains unnecessary items, that's why I have raised an issue to enhance the navbar. Refer #48 

Please review video to found the mistakes in navbar

Completed #42

### CODE REVIEW

**Comment by rishicds** [comment]
please fix conflicts @Shariq2003

**Comment by Shariq2003** [comment]
> please fix conflicts @Shariq2003

@rishicds okay just give me a minute

**Comment by rishicds** [comment]
still conflicts not resolved, take your time, no need to hurry @Shariq2003

**Comment by Shariq2003** [comment]
@rishicds sir, please stop merging PR before my PR

**Comment by Shariq2003** [comment]
As i have added routing

**Comment by rishicds** [comment]
ok not merging anymore prs @Shariq2003

**Comment by Shariq2003** [comment]
> ok not merging anymore prs @Shariq2003

Just give me 5 mints to assemble the new compo that have added now

**Comment by Shariq2003** [comment]
@rishicds sir please review and merge

**Comment by Shariq2003** [comment]
@rishicds sir

**Comment by rishicds** [comment]
Good job! @Shariq2003

**Comment by Shariq2003** [comment]
@rishicds please create a guideline for every user to follow project structure

**Pull request merged**
