### PR TITLE
Remove Redundant Data, Create New Hero section and Also Completely redesign the Landing Page | Issue #74

### PR DESCRIPTION
**Pull request by Shariq2003**
I have done the following tasks:-

1. Remove redundant data from the landing page (consisting of events, projects, teams, and gallery sections) for which dedicated pages are already there on the website.

2. Create a new Hero Section as per the GDSC Theme (Googler Theme) with proper styling.
3. Completely redesign the landing page ( as after removing redundant data, that becomes blank, only hero section left there ) by adding two section:-
    - Path to success  Vision, Mission and Goal.
    - Quote Section

https://github.com/user-attachments/assets/ef0be0d5-19f6-4656-b37e-573bbb3ecfcd

Completed #74

### CODE REVIEW

**Comment by Shariq2003** [comment]
@rishicds sir, please review  and merge

**Comment by rishicds** [comment]
fix conflicts

**Comment by Shariq2003** [comment]
> fix conflicts

Check now, sir

**Comment by Shariq2003** [comment]
@rishicds labels ?

**Pull request merged**
