### PR TITLE
Extended Resouce Page | Dynamic Routing of Resouces | Issue #87

### PR DESCRIPTION
**Pull request by Shariq2003**
I have implemented a single page for the extended content of the resources, that supports the Dynamic Routing of a Route.
E.g. Resources/[id]

It will extend the resources.
I also followed the modular approach that supports future enhancements in the resources easily( that I also used on all my pages)

https://github.com/user-attachments/assets/deb2120b-a770-42a7-a07a-61d4f90a8aa7

Completed #87

### CODE REVIEW

**Comment by rishicds** [comment]
please fix conflicts

**Comment by Shariq2003** [comment]
@rishicds sir, please check now

**Comment by rishicds** [comment]
Merged! Good job 👏🏼

**Comment by Shariq2003** [comment]
@rishicds sir labels ?

**Comment by rishicds** [comment]
Assigned labels

**Pull request merged**
