### PR TITLE
Update social media links in Footer component

### PR DESCRIPTION
**Pull request by amitb0ra**
Fixes: #180 
This PR updates the social media links in the Footer component to ensure they reflect the latest and correct URLs.

**Please add GSSoC'24 ext and hacktoberfest labels**

### CODE REVIEW

**Comment by rishicds** [comment]
have you created an issue? if yes please mention that

**Comment by amitb0ra** [comment]
> have you created an issue? if yes please mention that

no, not yet

**Comment by rishicds** [comment]
Create an issue first alsp attach screenshot of the changes u have made

**Comment by amitb0ra** [comment]
> Create an issue first alsp attach screenshot of the changes u have made

done, #180

**Comment by Shariq2003** [comment]
@rishicds this issue is raised by my, #172 
How @amitb0ra can raise a pull even without any issue assigned to him.

**Comment by Shariq2003** [comment]
@rishicds sir, please close this PR, as I am raising my PR of my issue.

**Comment by amitb0ra** [comment]
> @rishicds This issue was raised by my and also assigned to me, #172 How @amitb0ra can raise a pull even without any issue assigned to him similar like this?

I created PR before raising issue as i thought its a small issue. but i have done my PR 2 days before you. so can you consider it to close? also you won't mind giving this issue to me you are already in top 10 brother

@rishicds @Shariq2003

**Comment by sezallagwal** [comment]
> @rishicds sir, please close this PR, as I am raising PR of my issue.

He did a PR way before you raised an issue, so you should consider updating the title of your issue to remove the part which he already addressed in this PR. Also removing that part won’t impact the value of your issue as you've already highlighted multiple valuable points for improvement so It will still be a level 3

**Comment by Shariq2003** [comment]
> > @rishicds This issue was raised by my and also assigned to me, #172 How @amitb0ra can raise a pull even without any issue assigned to him similar like this?
> 
> I created PR before raising issue as i thought its a small issue. but i have done my PR 2 days before you. so can you consider it to close? also you won't mind giving this issue to me you are already in top 10 brother
> 
> @rishicds @Shariq2003

Bro I am not saying that you are just copying my issue, or I need more points, No..
I am just addressing the gssoc guidelines in which it is mentioned there to raise issue first rather than PR, no matter the size of issue, you first have to wait the for assignment

**Pull request closed without merging**
