### PR TITLE
Added User Testimonials and Achievements

### PR DESCRIPTION
**Pull request by ananyag309**
#190

https://www.loom.com/share/14779fe1c0a84c3ba9fe90e205b1d37a?sid=62382537-2c8a-4284-b3d8-448f2a71ba3a

screenshot

image

image

### CODE REVIEW

**Comment by rishicds** [comment]
cab you fix the conflicts

**Comment by ananyag309** [comment]
@rishicds i have resolved the conflicts, please review it and merge it as soon as possible as the open source going to end soon

**Comment by Shariq2003** [comment]
> @rishicds i have resolved the conflicts, please review it and merge it as soon as possible as the open source going to end soon

@ananyag309 sorry, but the homepage is totally messed up, after merging this branch,
You have merged incorrectly the conflicting code,

Closing tags without opening.......
Refer the below images.

image

image

image

**Comment by Shariq2003** [comment]
@rishicds please always try to take a followup video of UI after any kind of merge conflicts

**Comment by ananyag309** [comment]
@Shariq2003 its running on my side of the code ...hows that possible?

**Comment by ananyag309** [comment]
Is it due to I clicked on resolved conflicts? Cuz the code changes I made is perfectly good and working

**Comment by Shariq2003** [comment]
> @Shariq2003 its running on my side of the code ...hows that possible?

I have raised a PR for the fixes, that have merged.

**Comment by Shariq2003** [comment]
#334

**Comment by Shariq2003** [comment]
> @Shariq2003 its running on my side of the code ...hows that possible?

#276

**Pull request merged**
