### PR TITLE
Multiple UI/UX Enhancements and Fixes 

### LINKED ISSUE #85: Multiple UI/UX Enhancements and Fixes
1. Return to Home Page on Logo Click
Description: Ensure that clicking the logo on the navigation bar returns the user to the home page.
2. Add a Light Gradient Background to Events Page
Description: Implement a light gradient background on the Events page to enhance the visual appeal and improve user experience.
3. Fix Unused Footer on About Page
Description: Resolve the issue of the unused or unoptimized footer on the About page to make it more functional and visually aligned with the overall design.
4. Optimize Colors for Existing Progress Bar
Description: Adjust the colors of the current progress bar to ensure better readability and consistency with the overall theme of the application.

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix #85
- **Return to Home Page on Logo Click**
- **Add a Light Gradient Background to Events Page**
Screenshot 2024-10-23 at 9 32 24 PM
-  **Fix footer styling** 
Screenshot 2024-10-23 at 9 32 44 PM
- **Optimize Colors for Existing Progress Bar**
image

Hey @rishicds please review my PR.

### CODE REVIEW

**Review by MastanSayyad — COMMENTED** [review]
Hi Basic css changes with multiple code formatting

@rishicds please reduce the level to `level 1`
reasons:
- lot of code formatting (which increased the number of lines)
- basic CSS UI changes
- no new addition of feature or creation

**Comment by shubhagarwal1** [comment]
> Hi Basic css changes with multiple code formatting
> 
> @rishicds please reduce the level to `level 1` reasons:
> 
> * lot of code formatting (which increased the number of lines)
> * basic CSS UI changes
> * no new addition of feature or creation
> 
> image

As you mentioned earlier, enhaching the code with only few lines can have level 1, so as this changes are marked to be multiple, i understasdn that level3 is not valid but level for these multiple changes would be decent, if not please guide me

**Comment by shubhagarwal1** [comment]
> Hi Basic css changes with multiple code formatting
> 
> @rishicds I'm reducing the level to `level 1` reasons:
> 
> * lot of code formatting (which increased the number of lines)
> * basic CSS UI changes
> * no new addition of feature or creation
> 
> image

**Comment by MastanSayyad** [comment]
@shubhagarwal1 given the reasons, you just enhance the existing code bro

image

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 given the reasons, you just enhance the existing code bro
> 
> image

Hey i understasnd the review session is going on, i respectfully obeys the review and has no objection with this

**Pull request merged**
