### PR TITLE
Enhance TeamsGallery Page | Issue #61

### PR DESCRIPTION
**Pull request by Shariq2003**
I have redesigned the whole teams and gallery page, along with the styling to match the website's theme.

I have written the code in modular approach.

https://github.com/user-attachments/assets/08b26390-421c-4294-93a3-a100225aa2a5

Completed #61 

### **NOTE**
@rishicds sir I am having issues in the service implementation of LinkedIn User Profile Photo Fetch by LinkedIn Profile Link as the LinkedIn policies are now a bit changed that require the OAuth as a member by their Profile_IDs. For which we have to gather all the members' LinkedIn Profile_ID, along with the visibility option enabled by them, which makes this service implementation a bit tough for your management team (in the future).

That's why, for now, I have implemented the modular approach to store the team's data in a separate file that can be easily manageable, along with the UI Enhancements for better UX.

### CODE REVIEW

**Comment by rishicds** [comment]
oh okay if possible fix the conflicts, if it is a lot of work you can raise another issue related to this ill assign levels

**Comment by Shariq2003** [comment]
> oh okay if possible fix the conflicts, if it is a lot of work you can raise another issue related to this ill assign levels


🥲, fixing the conflicts

**Comment by Shariq2003** [comment]
@rishicds also check this

**Comment by Shariq2003** [comment]
@rishicds sir, also add labels to my previous PR.

**Comment by NEGRAH-S** [comment]
@MastanSayyad , Level 2 as page was already Made and only UI Enhancement were made

**Pull request merged**
