### PR TITLE
Feat loading page

### PR DESCRIPTION
**Pull request by dev129**
Hi @rishicds 
#### Issue Title
**Add Loading Page at the Start of Website**  

- [x] Issue title provided.

---

#### Info about the Related Issue
The project aims to enhance the user experience by displaying a loading screen when the website starts.

- [x] Project goal described.

---

#### Name
Devansh Vishwa

- [x] Name provided.

---

#### GitHub ID
dev129

- [x] GitHub ID provided.

---

#### Identify Yourself
Contributor in GSSOC-EXT

- [x] Program participation mentioned.

---

#### Closes
Closes: #397 

- [x] Issue number provided.

---

#### Describe the Add-ons or Changes You've Made
Added a loading video component to display at the start of the website, indicating that content is loading.

- [x] Changes described.

---

#### Type of Change
- [x] New feature (non-breaking change which adds functionality)

---

#### How Has This Been Tested?
The loading screen was tested across different devices and browsers to ensure it appears correctly and transitions smoothly into the main content.

- [x] Testing process described.

---

#### Checklist
- [x] Code follows project guidelines.
- [x] Self-review completed.
- [x] Code comments added where needed.
- [x] Documentation updated as necessary.
- [x] No new warnings generated.
- [x] Evidence provided that the feature works effectively.

### Screenshots:
image
image

### Videos:

https://github.com/user-attachments/assets/e1344f7b-1b83-446b-8f58-e3276adce464

### CODE REVIEW

**Comment by rishicds** [comment]
Awesome, can you tell which software you used to make this animation

**Comment by dev129** [comment]
@rishicds , I used canva for editing and this was already a video used by a GDSC club, relax you won't receive any copyright.

**Comment by rishicds** [comment]
> @rishicds , I used canva for editing and this was already a video used by a GDSC club, relax you won't receive any copyright.

Not for copyright I'll implement it a bit differently

**Comment by dev129** [comment]
I used canva for basic editing but you can hire a video editor , who can help you design.

**Pull request merged**
