### PR TITLE
BUG Fix | Issue #67

### LINKED ISSUE #67: URGENT : BUG : Main Branch Package.json corruption | Duplicate Vlaues Containes | By the Merging of PR #65
image

Look at this, 

image

Contains duplicate dependencies

### PR DESCRIPTION
**Pull request by Shariq2003**
Fix #67 

image

### CODE REVIEW

**Comment by Shariq2003** [comment]
@rishicds sir, review and merge

**Comment by Shariq2003** [comment]
@rishicds sir, could u please merge this asap, so that we can proceed to our assigned tasks.

**Review by MastanSayyad — COMMENTED** [review]
dependencies should not have level 3 surely it fixes the bug but can only considered as level 1

**Comment by Shariq2003** [comment]
> dependencies should not have level 3 surely it fixes the bug but can only considered as level 1

@MastanSayyad it should be of at least level 2, because its a BUG

**Pull request merged**
