### PR TITLE
Added BackToTop Button with Smooth Scrolling | Issue #59

### PR DESCRIPTION
**Pull request by Shariq2003**
I have implemented and added the BackToTop button in the website, with smooth scrolling.

https://github.com/user-attachments/assets/ae1159ba-146b-4858-bbcc-4596b9ac1555

Completed #59

### CODE REVIEW

**Comment by Shariq2003** [comment]
Fixing the Conflicts

**Comment by Shariq2003** [comment]
> Fixing the Conflicts

@rishicds sir, check now.

**Comment by Shariq2003** [comment]
Labels @rishicds Sir ?

**Comment by Shariq2003** [comment]
@rishicds sir, u have not added labels

**Comment by Shariq2003** [comment]
@rishicds sir, u have not added labels

**Comment by rishicds** [comment]
Added

**Comment by Shariq2003** [comment]
> Added

Thanks a lot sir

**Review by MastanSayyad — COMMENTED** [review]
The button has standard functionalities that a normal scroll to top button has therefore it should have level 1

**Pull request merged**
