### PR TITLE
Uniform Theme For website 

### PR DESCRIPTION
**Pull request by dev129**
### Pull Request: Establish Uniform Theme with Color Codes

**Issue**: #123 

Uploading bandicam 2024-10-28 11-40-19-780.mov…

Hi  @rishicds 

#### Summary
This pull request aims to implement a consistent design theme across the website, drawing inspiration from the Google Developer Student Club's branding. The primary background color has been set to `#1D4ED8` (bg-blue-500), with `#1E40AF` (bg-blue-600) designated as the secondary color to ensure a cohesive and polished look throughout all pages.

#### Changes Made
- **Color Consistency**: Implemented the primary color `#1D4ED8` for key components and `#1E40AF` as a secondary color, ensuring a uniform design across the website.
- **Typography**: Established consistent font styles and sizes for headings, body text, and buttons to enhance readability and maintain a unified appearance.
- **Reusable Components**: Developed reusable UI components (such as buttons and cards) that align with the established design principles, promoting consistency and efficiency in the codebase.
- **Spacing & Alignment**: Standardized margins and paddings across various elements to achieve a balanced and visually appealing layout.
- **Responsive Design**: Ensured all design elements are responsive, maintaining a consistent look across different devices and screen sizes.

#### Testing
- Verified the rendering of all components across multiple browsers and devices to ensure visual consistency.
- Conducted usability testing to confirm that the new design enhances user experience without introducing any issues.

#### Additional Notes
This theme enhancement is intended to create a visually appealing and cohesive user interface. Future updates may include expanding the color palette to incorporate additional accent colors.

### CODE REVIEW

**Comment by rishicds** [comment]
can u upload video once it hasnt been uploaded

**Comment by dev129** [comment]
https://github.com/user-attachments/assets/a6f373d1-5682-42e0-ae7d-e7b8fa969e94

**Comment by dev129** [comment]
Hi @rishicds , let me know if any further changes are needed.

**Comment by dev129** [comment]
Hi @rishicds , please check my PR.

**Comment by rishicds** [comment]
fix conflicts please

**Comment by rishicds** [comment]
upload a video after fixing conflicts, new header should be there

**Comment by rishicds** [comment]
@dev129 can you send  a screenshot that will suffice no need video

**Comment by rishicds** [comment]
theme already settled

**Pull request closed without merging**
